- .gitignore
- Dockerfile
- circle.yml
Migrated source AMI to Covalence image and pull in binaries from other Docker images
> Move to Alpine based image

- Dockerfile
This is what was keeping module RPC from functioning properly
> Added glibc for Packer module RPC

- Dockerfile
- circle.yml
Reverts unifio/dockerfile-ci#7
> Revert "Adding node and npm to ci"

- .circleci/config.yml
- Dockerfile-node
- Gemfile
- copybins.sh
- docker-compose.yml
- spec/node_spec.rb
- tools/covalence/.gemrc
- tools/covalence/Gemfile
- tools/covalence/Gemfile.lock
Adds CI container based on the official node container.
> Node.js CI container

- Dockerfile-node
- tools/covalence/Gemfile
Including Dockerspec to cut down the time to install native gems downstream
> Updated packages included in node container

- .circleci/config.yml
- tools/covalence/uat/data/stacks/vpc.yaml
Not sure how we've not seen it before now, but the UAT stacks were colliding.
> Update to avoid UAT stack collision

- .circleci/config.yml
* Updated terraform version to 0.11.4
> Updating to terraform 0.11.4

- .circleci/config.yml
* Updating to the latest terraform
> Updating to terraform 0.11.5

- .circleci/config.yml
- spec/infra_spec.rb
* Updating terraform to version 0.11.12
> Updating terraform to version 0.11.12

- .circleci/config.yml
* Updating to terraform 0.11.13
> Updating to terraform 0.11.13

- .circleci/config.yml
- README.md
* Updated packer to version 1.4.4
* Added microsoft teams integration for OSS channel notifications.
> Updating Packer to 1.4.4 added MS Teams Notification

- .circleci/config.yml
- README.md
* Upgrade terraform to 0.12.11
> Upgrade terraform to 0.12.11

- .circleci/config.yml
- README.md
* Updating terraform to 0.12.13
> Upgrade terraform to 0.12.13

- .circleci/config.yml
- README.md
> Update packer 1.4.5

- .circleci/config.yml
- README.md
* Updating terraform to 0.12.16
> Updating terraform to 0.12.16

- .circleci/config.yml
- README.md
* Updating terraform to 0.12.17
> Terraform 0.12.17 update

- .circleci/config.yml
- README.md
> Update to Terraform 0.12.18

- .circleci/config.yml
- Gemfile.lock
- README.md
- tools/covalence/Gemfile.lock
* Fixing a rack vulnerability in the gems 
* Updating to terraform to 0.12.19
> Fix rack vulnerability / Upgrade TF to 0.12.19

- .circleci/config.yml
- README.md
Upgrading terraform from 0.12.20 to 0.12.21
> Upgrading terraform from 0.12.20 to 0.12.21

- .circleci/config.yml
- Dockerfile-infra
- Dockerfile-node
- README.md
- tools/covalence/Dockerfile
> Updating SOPS version 3.5.0

- .circleci/config.yml
- README.md
> TF upgrade 0.12.22

- .circleci/config.yml
- README.md
* Upgrading terraform to 0.12.25
> Upgrading Terraform to 0.12.25

- .circleci/config.yml
- README.md
* Upgrade to Terraform 0.12.26
> Upgrade to Terraform 0.12.26

- .circleci/config.yml
- README.md
- tools/packer/Dockerfile
* Updating to packer version 1.6.0
* Updating to packer-provisioner-serverspec v0.2.1
> Updating to packer 1.6.0

- .circleci/config.yml
- README.md
> Update terraform to 0.12.27

- .circleci/config.yml
- README.md
> Update Terraform to 0.12.28

- .circleci/config.yml
- README.md
* Updating to terraform 0.12.29
> Updating to terraform 0.12.29

- .circleci/config.yml
- README.md
* Upgraded packer to 1.6.3 adds assume_role to packer similar to terraform.
> Upgrade packer to 1.6.3 adds assume_role 
